### ISSUE TITLE
White Outline in right click menu

### ISSUE THREAD

**Issue by Techpotato1** [MGGSK/DarkMenus#17]
**Describe the bug**

When updating to the latest version of the mod, there's now a white outline on my right click menu. The other dark menus are fine. 

**To Reproduce**

Right Click on the desktop or within file explorer.

**Screenshots**

<img width="274" height="337" alt="Image" src="https://github.com/user-attachments/assets/cb5d0671-ae3e-495f-a3d3-ec0157d937d4" />

<img width="270" height="697" alt="Image" src="https://github.com/user-attachments/assets/ec046d44-59b6-4c4a-abcf-638d7f07799a" />

**Device info:**
 - Windows build: 26100.7462
 - Mod version: 1.3.3

**Comment by MaxLHy0424** [comment]
I have the same problem. This bug also exists on Windows 11 Build 26220.7523.

**Comment by Meteony** [comment]
Same

**Comment by MGGSK** [comment]
I just submitted the fix to the official repo.

**Comment by MGGSK** [comment]
The mod is now fixed.

**Comment by milroneth** [comment]
This is not fixed for me in 1.3.4 on Windows 10. First time loading the desktop context menu after loading the mod it looks ok, subsequent menus get the thick border. Reverting to 1.3.2 fixes this. Windhawk 1.7.3

**Comment by MGGSK** [comment]
> This is not fixed for me in 1.3.4 on Windows 10. First time loading the desktop context menu after loading the mod it looks ok, subsequent menus get the thick border. Reverting to 1.3.2 fixes this. Windhawk 1.7.3

This is caused by a different issue reported in https://github.com/MGGSK/DarkMenus/issues/18.

**Comment by isxmiyulll** [comment]
I've just updated it and I can't tell whether it fixed it. It still shows the white outline but when I disable the mod, it goes.

**Comment by MGGSK** [comment]
> I've just updated it and I can't tell whether it fixed it. It still shows the white outline but when I disable the mod, it goes.

The bug still shows up sometimes, but I already found a better fix which will be in version 1.4.

**Comment by NotADeveloper97** [comment]
I never had this pre 1.3.4 and after i updated it shows up??

**Comment by MGGSK** [comment]
The fix will be in version 1.4.
